# Automatically generated by Honest Code
# Do not edit this file as it will be overwritten

Feature: New player
  As an API cliente
  I want to create a new player

  Scenario: POST /player 200 OK with valid body
    When I request to create a new player with following data
      | email                 | fullname   | avatar          | idp    | idp_id |
      | kara.trace@domain.com | Kara Trace | http://kara.jpg | google | 1      |
    Then the response status code is 201
    And the response body has an "id" field

  Scenario: POST /player 200 OK
    When I request to create a new player with following data
      | email                 | fullname   | avatar          | idp    | idp_id |
      | kara-trace@domain.com | Kara Trace | http://kara.jpg | google | 1      |
    And I request to find a player with following search parameters
      | field  | value  |
      | idp    | google |
      | idp_id | 1      |
    Then the response status code is 200
    And the response body has a list field "items" with 1 length
    And the response body item 0 has a "id" field
    And the response body item 0 has a "creationDate" field
    And the response body item 0 has a "fullname" field with "Kara Trace" value
    And the response body item 0 has a "email" field with "kara-trace@domain.com" value
    And the response body item 0 has a "avatar" field with "http://kara.jpg" value
    And the response body item 0 does not have a "idp" field
